# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Configura o SwiftLint...."
  lane :install_swiftlint do
    sh <<-SHELL
      if ! which swiftlint > /dev/null; then
        brew install swiftlint
      else
        echo 'SwiftLint já está instalado'
      fi
    SHELL
  end

  desc "Testes Unitários...."
  lane :unit_tests do
  scan(
      scheme: "DigioStore", 
      device: "iPhone 8",
      clean: true,
      test_without_building: false,
      code_coverage: true
    )
  end
end
